apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: argocd
servers: 1
agents: 2
ports:
  - port: 8080:30000
    nodeFilters:
     - loadbalancer
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer