apiVersion: v1
kind: Namespace
metadata:
  name: web

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-color
  namespace: web
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: web-color
  template:
    metadata:
      labels:
        app: web-color
    spec:
      containers:
      - name: web-color
        image: fabricioveronez/web-color:blue
        resources:
          limits:
            cpu: "0.2"
          requests:
            cpu: "0.1"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: svc-web-color
  namespace: web
spec:
  selector:
      app: web-color
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
      nodePort: 30000
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web
  namespace: web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
  - host: webcolor.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-web-color
            port:
              number: 8080